method: onet
data:
  dataset: Shapes3D
  path: data/ShapeNet
  classes: null
  input_type: img
  train_split: train
  val_split: val
  test_split: test
  dim: 3
  points_file: points.npz
  points_iou_file: points.npz
  points_subsample: 1024
  points_unpackbits: true
  model_file: model.off
  watertight_file: model_watertight.off
  img_folder: img
  img_size: 224 
  img_with_camera: false
  img_augment: false
  n_views: 24
  pointcloud_file: pointcloud.npz
  pointcloud_chamfer_file: pointcloud.npz
  pointcloud_n: 256
  pointcloud_target_n: 1024
  pointcloud_noise: 0.05
  pointcloud_hole: false
  pointcloud_outlier: false
  voxels_file: 'model.binvox'
  with_transforms: false
  sample_dense_surf: false
  sample_near_surf: false
model:
  decoder: simple
  encoder: resnet18
  encoder_latent: null
  decoder_kwargs: {}
  encoder_kwargs: {}
  encoder_latent_kwargs: {}
  multi_gpu: false
  npoint: 4096
  c_dim: 512
  z_dim: 64
  local_frame: True
  K: 8
  resolution: 32
  use_camera: false
  dmc_weight_prior: 10.
  identifier: simple_resnet18
  sample_around_surf: False
  stage: 0
training:
  out_dir:  out/default
  max_epochs: 25000
  batch_size: 64
  print_per_batch: 2000
  skip_training: false
  checkpoint_every: 5
  validate_every: 5
  validate_dense_every: 25
  visualize_every: 5
  backup_every: 5
  eval_sample: false
  model_selection_metric: loss
  model_selection_mode: minimize
  b_domain_transfer: false
## optimizer cfgs
  optimizer: ADAM
  lr: 0.0001
  scheduler: null
  scheduler_params: null
## overfit testing or not
  overfit: 0
test:
  batch_size: 2
  threshold: 0.5
  points_per_batch: 100000
  eval_mesh: true
  eval_pointcloud: true
  model_file: model_best.pt
generation:
  batch_size: 100000
  refinement_step: 0
  vis_n_outputs: 30
  generate_mesh: true
  generate_pointcloud: true
  generation_dir: generation
  use_sampling: false
  resolution_0: 32
  upsampling_steps: 2
  simplify_nfaces: null
  copy_groundtruth: false
  copy_input: true
  latent_number: 4
  latent_H: 8
  latent_W: 8
  latent_ny: 2
  latent_nx: 2
  latent_repeat: true
preprocessor:
  type: null
  config: ""
  model_file: null
